service: avatar-generator-rabbit

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'